version: '3'

services:
  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ollama_models:/root/.ollama
    ports:
      - "${OLLAMA_LOCAL}:${OLLAMA_API}"
    deploy:
      resources:
        reservations:
          devices:
          - driver: nvidia
            capabilities: ["gpu"]
            count: all
    restart: always
  
  api:
    build: ./app
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_URL=http://ollama:11434
    depends_on:
      - ollama
    restart: always


volumes:
  ollama_models:
    name: ollama_models